// Code generated by protoc-gen-go. DO NOT EDIT.
// source: garage.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GarageCoordinate struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GarageCoordinate) Reset()         { *m = GarageCoordinate{} }
func (m *GarageCoordinate) String() string { return proto.CompactTextString(m) }
func (*GarageCoordinate) ProtoMessage()    {}
func (*GarageCoordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35248283e3db3c1, []int{0}
}

func (m *GarageCoordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageCoordinate.Unmarshal(m, b)
}
func (m *GarageCoordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageCoordinate.Marshal(b, m, deterministic)
}
func (m *GarageCoordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageCoordinate.Merge(m, src)
}
func (m *GarageCoordinate) XXX_Size() int {
	return xxx_messageInfo_GarageCoordinate.Size(m)
}
func (m *GarageCoordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageCoordinate.DiscardUnknown(m)
}

var xxx_messageInfo_GarageCoordinate proto.InternalMessageInfo

func (m *GarageCoordinate) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GarageCoordinate) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Garage struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coordinate           *GarageCoordinate `protobuf:"bytes,3,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Garage) Reset()         { *m = Garage{} }
func (m *Garage) String() string { return proto.CompactTextString(m) }
func (*Garage) ProtoMessage()    {}
func (*Garage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35248283e3db3c1, []int{1}
}

func (m *Garage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Garage.Unmarshal(m, b)
}
func (m *Garage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Garage.Marshal(b, m, deterministic)
}
func (m *Garage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Garage.Merge(m, src)
}
func (m *Garage) XXX_Size() int {
	return xxx_messageInfo_Garage.Size(m)
}
func (m *Garage) XXX_DiscardUnknown() {
	xxx_messageInfo_Garage.DiscardUnknown(m)
}

var xxx_messageInfo_Garage proto.InternalMessageInfo

func (m *Garage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Garage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Garage) GetCoordinate() *GarageCoordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

type GarageList struct {
	List                 []*Garage `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GarageList) Reset()         { *m = GarageList{} }
func (m *GarageList) String() string { return proto.CompactTextString(m) }
func (*GarageList) ProtoMessage()    {}
func (*GarageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35248283e3db3c1, []int{2}
}

func (m *GarageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageList.Unmarshal(m, b)
}
func (m *GarageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageList.Marshal(b, m, deterministic)
}
func (m *GarageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageList.Merge(m, src)
}
func (m *GarageList) XXX_Size() int {
	return xxx_messageInfo_GarageList.Size(m)
}
func (m *GarageList) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageList.DiscardUnknown(m)
}

var xxx_messageInfo_GarageList proto.InternalMessageInfo

func (m *GarageList) GetList() []*Garage {
	if m != nil {
		return m.List
	}
	return nil
}

type GarageListByMember struct {
	List                 map[string]*GarageList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GarageListByMember) Reset()         { *m = GarageListByMember{} }
func (m *GarageListByMember) String() string { return proto.CompactTextString(m) }
func (*GarageListByMember) ProtoMessage()    {}
func (*GarageListByMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35248283e3db3c1, []int{3}
}

func (m *GarageListByMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageListByMember.Unmarshal(m, b)
}
func (m *GarageListByMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageListByMember.Marshal(b, m, deterministic)
}
func (m *GarageListByMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageListByMember.Merge(m, src)
}
func (m *GarageListByMember) XXX_Size() int {
	return xxx_messageInfo_GarageListByMember.Size(m)
}
func (m *GarageListByMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageListByMember.DiscardUnknown(m)
}

var xxx_messageInfo_GarageListByMember proto.InternalMessageInfo

func (m *GarageListByMember) GetList() map[string]*GarageList {
	if m != nil {
		return m.List
	}
	return nil
}

type GarageMemberId struct {
	MemberId             string   `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GarageMemberId) Reset()         { *m = GarageMemberId{} }
func (m *GarageMemberId) String() string { return proto.CompactTextString(m) }
func (*GarageMemberId) ProtoMessage()    {}
func (*GarageMemberId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35248283e3db3c1, []int{4}
}

func (m *GarageMemberId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageMemberId.Unmarshal(m, b)
}
func (m *GarageMemberId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageMemberId.Marshal(b, m, deterministic)
}
func (m *GarageMemberId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageMemberId.Merge(m, src)
}
func (m *GarageMemberId) XXX_Size() int {
	return xxx_messageInfo_GarageMemberId.Size(m)
}
func (m *GarageMemberId) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageMemberId.DiscardUnknown(m)
}

var xxx_messageInfo_GarageMemberId proto.InternalMessageInfo

func (m *GarageMemberId) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

type GarageAndMemberId struct {
	MemberId             string   `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Garage               *Garage  `protobuf:"bytes,2,opt,name=garage,proto3" json:"garage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GarageAndMemberId) Reset()         { *m = GarageAndMemberId{} }
func (m *GarageAndMemberId) String() string { return proto.CompactTextString(m) }
func (*GarageAndMemberId) ProtoMessage()    {}
func (*GarageAndMemberId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35248283e3db3c1, []int{5}
}

func (m *GarageAndMemberId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageAndMemberId.Unmarshal(m, b)
}
func (m *GarageAndMemberId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageAndMemberId.Marshal(b, m, deterministic)
}
func (m *GarageAndMemberId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageAndMemberId.Merge(m, src)
}
func (m *GarageAndMemberId) XXX_Size() int {
	return xxx_messageInfo_GarageAndMemberId.Size(m)
}
func (m *GarageAndMemberId) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageAndMemberId.DiscardUnknown(m)
}

var xxx_messageInfo_GarageAndMemberId proto.InternalMessageInfo

func (m *GarageAndMemberId) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *GarageAndMemberId) GetGarage() *Garage {
	if m != nil {
		return m.Garage
	}
	return nil
}

func init() {
	proto.RegisterType((*GarageCoordinate)(nil), "proto.GarageCoordinate")
	proto.RegisterType((*Garage)(nil), "proto.Garage")
	proto.RegisterType((*GarageList)(nil), "proto.GarageList")
	proto.RegisterType((*GarageListByMember)(nil), "proto.GarageListByMember")
	proto.RegisterMapType((map[string]*GarageList)(nil), "proto.GarageListByMember.ListEntry")
	proto.RegisterType((*GarageMemberId)(nil), "proto.GarageMemberId")
	proto.RegisterType((*GarageAndMemberId)(nil), "proto.GarageAndMemberId")
}

func init() { proto.RegisterFile("garage.proto", fileDescriptor_d35248283e3db3c1) }

var fileDescriptor_d35248283e3db3c1 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0x69, 0x0b, 0x3c, 0x3a, 0xbc, 0x47, 0x60, 0x92, 0xa7, 0x4d, 0xf1, 0x80, 0x6b, 0x8c,
	0x5c, 0x2c, 0x49, 0x3d, 0xa0, 0xde, 0xd0, 0x10, 0xa3, 0xc1, 0x4b, 0x2f, 0x1e, 0x4d, 0x71, 0xd7,
	0xa6, 0xb1, 0x3f, 0x48, 0x59, 0x8c, 0xfd, 0x53, 0xfc, 0x6f, 0x0d, 0x3b, 0xa5, 0x50, 0xb8, 0x78,
	0xda, 0x9d, 0xf9, 0xcc, 0x77, 0x7e, 0x65, 0xe0, 0x6f, 0xe0, 0x67, 0x7e, 0x20, 0x9c, 0x45, 0x96,
	0xca, 0x14, 0x1b, 0xea, 0xb1, 0xfb, 0x41, 0x9a, 0x06, 0x91, 0x18, 0x29, 0x6b, 0xbe, 0x7a, 0x1f,
	0x89, 0x78, 0x21, 0x73, 0x8a, 0x61, 0x33, 0xe8, 0x3e, 0x28, 0xcd, 0x7d, 0x9a, 0x66, 0x3c, 0x4c,
	0x7c, 0x29, 0xd0, 0x86, 0x56, 0xe4, 0xcb, 0x50, 0xae, 0xb8, 0xb0, 0xb4, 0x81, 0x36, 0xd4, 0xbd,
	0xd2, 0xc6, 0x13, 0x30, 0xa3, 0x34, 0x09, 0x08, 0xea, 0x0a, 0x6e, 0x1d, 0x4c, 0x40, 0x93, 0xb2,
	0x61, 0x07, 0xf4, 0x90, 0x2b, 0xb5, 0xe9, 0xe9, 0x21, 0x47, 0x84, 0x7a, 0xe2, 0xc7, 0x24, 0x31,
	0x3d, 0xf5, 0xc7, 0x31, 0xc0, 0x5b, 0x59, 0xd5, 0x32, 0x06, 0xda, 0xb0, 0xed, 0x1e, 0x53, 0x5f,
	0xce, 0x7e, 0x53, 0xde, 0x4e, 0x28, 0x1b, 0x01, 0x10, 0x9f, 0x85, 0x4b, 0x89, 0xa7, 0x50, 0x8f,
	0xc2, 0xa5, 0xb4, 0xb4, 0x81, 0x31, 0x6c, 0xbb, 0xff, 0x2a, 0x09, 0x3c, 0x85, 0xd8, 0xb7, 0x06,
	0xb8, 0x55, 0xdc, 0xe5, 0xcf, 0x22, 0x9e, 0x8b, 0x0c, 0xc7, 0x15, 0xe5, 0x59, 0x45, 0xb9, 0x1b,
	0xe8, 0xac, 0x8d, 0x69, 0x22, 0xb3, 0x9c, 0xf2, 0xd9, 0x4f, 0x60, 0x96, 0x2e, 0xec, 0x82, 0xf1,
	0x21, 0xf2, 0x62, 0xd6, 0xf5, 0x17, 0x2f, 0xa0, 0xf1, 0xe9, 0x47, 0x2b, 0x9a, 0xb6, 0xed, 0xf6,
	0x0e, 0x12, 0x7b, 0xc4, 0x6f, 0xf5, 0x6b, 0x8d, 0x5d, 0x42, 0x87, 0x00, 0xd5, 0x7a, 0xe4, 0xd8,
	0x07, 0x33, 0x56, 0xff, 0xd7, 0x72, 0x85, 0xad, 0xb8, 0x80, 0xec, 0x05, 0x7a, 0x14, 0x3e, 0x49,
	0xf8, 0xaf, 0x14, 0x78, 0x0e, 0x4d, 0x3a, 0x8b, 0xa2, 0x9d, 0xbd, 0x0d, 0x15, 0xd0, 0xfd, 0x82,
	0x3f, 0xe4, 0x59, 0xa2, 0x0b, 0x75, 0xb5, 0xd9, 0xff, 0x95, 0xc8, 0x4d, 0x35, 0xfb, 0x70, 0x1e,
	0x56, 0xc3, 0x1b, 0x30, 0x26, 0x9c, 0xa3, 0x55, 0x61, 0x3b, 0x3d, 0xda, 0x47, 0x0e, 0xdd, 0xa1,
	0xb3, 0xb9, 0x43, 0x67, 0xba, 0xbe, 0x43, 0x56, 0x9b, 0x37, 0x95, 0xe7, 0xea, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xb4, 0xd0, 0x82, 0x9d, 0xbe, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GaragesClient is the client API for Garages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GaragesClient interface {
	List(ctx context.Context, in *GarageMemberId, opts ...grpc.CallOption) (*GarageList, error)
	Add(ctx context.Context, in *GarageAndMemberId, opts ...grpc.CallOption) (*empty.Empty, error)
}

type garagesClient struct {
	cc *grpc.ClientConn
}

func NewGaragesClient(cc *grpc.ClientConn) GaragesClient {
	return &garagesClient{cc}
}

func (c *garagesClient) List(ctx context.Context, in *GarageMemberId, opts ...grpc.CallOption) (*GarageList, error) {
	out := new(GarageList)
	err := c.cc.Invoke(ctx, "/proto.Garages/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garagesClient) Add(ctx context.Context, in *GarageAndMemberId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Garages/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GaragesServer is the server API for Garages service.
type GaragesServer interface {
	List(context.Context, *GarageMemberId) (*GarageList, error)
	Add(context.Context, *GarageAndMemberId) (*empty.Empty, error)
}

// UnimplementedGaragesServer can be embedded to have forward compatible implementations.
type UnimplementedGaragesServer struct {
}

func (*UnimplementedGaragesServer) List(ctx context.Context, req *GarageMemberId) (*GarageList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedGaragesServer) Add(ctx context.Context, req *GarageAndMemberId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterGaragesServer(s *grpc.Server, srv GaragesServer) {
	s.RegisterService(&_Garages_serviceDesc, srv)
}

func _Garages_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GarageMemberId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaragesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Garages/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaragesServer).List(ctx, req.(*GarageMemberId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Garages_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GarageAndMemberId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaragesServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Garages/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaragesServer).Add(ctx, req.(*GarageAndMemberId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Garages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Garages",
	HandlerType: (*GaragesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Garages_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Garages_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "garage.proto",
}
